# Note this is a test version of the Docker Compose configuration, so there are no web or keycloak containers
version: '3.8'
services:
  database:
    image: 'postgres:13.1-alpine'
    container_name: database
    # XXX: we only publish 5432 in the development version. The production version should NOT publish the db port
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_MULTIPLE_DATABASES: care_quality_dashboard,keycloak,test
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: cqdashboard
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.txt
      - ./setup-db.sh:/docker-entrypoint-initdb.d/setup-db.sh
      - ./postgres:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro
