version: '3.8'
services:
  web:
    user: '1001:1001'
    image: 'docker.pkg.github.com/uclcomputerscience/comp0016_2020_21_team20/care-quality-dashboard-web:latest'
    container_name: web
    depends_on:
      - database
    ports:
      - '127.0.0.1:3000:3000'
    env_file:
      - .env
  keycloak:
    image: 'jboss/keycloak'
    container_name: keycloak
    depends_on:
      - database
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /tmp/keycloak/care_quality_dashboard_realm.json
      DB_VENDOR: postgres
      DB_ADDR: database
      DB_USER: cqdashboard
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      PROXY_ADDRESS_FORWARDING: 'true'
    volumes:
      - ./keycloak:/tmp/keycloak
      - ./keycloak/register.ftl:/opt/jboss/keycloak/themes/base/login/register.ftl
  # Note: no need to publish postgres port; all containers running on same network!
  database:
    user: '1001:1001'
    image: 'postgres:13.1-alpine'
    container_name: database
    environment:
      POSTGRES_MULTIPLE_DATABASES: care_quality_dashboard,keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: cqdashboard
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.txt
      - ./setup-db.sh:/docker-entrypoint-initdb.d/setup-db.sh
      - ./postgres:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro
