version: '3.8'
services:
  web:
    build: .
    container_name: web
    depends_on:
      - database
    ports:
      - '127.0.0.1:3000:3000'
    env_file:
      - .env
  keycloak:
    image: 'jboss/keycloak'
    container_name: keycloak
    depends_on:
      - database
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /tmp/nhsw_self_assessment_realm.json
      DB_VENDOR: postgres
      DB_ADDR: database
      DB_USER: nhsw-self-assessment
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./nhsw_self_assessment_realm.json:/tmp/nhsw_self_assessment_realm.json
  # Note: no need to publish postgres port; all containers running on same network!
  database:
    image: 'postgres:13.1-alpine'
    container_name: database
    environment:
      POSTGRES_MULTIPLE_DATABASES: nhsw_self_assessment,keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: nhsw-self-assessment
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.txt
      - ./setup-db.sh:/docker-entrypoint-initdb.d/setup-db.sh
      - ./postgres:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro
