name: Deploy backend API spec

on:
  push:
    branches:
      - main
jobs:
  deploy-backend-api-spec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install swagger-jsdoc
        run: npm install swagger-jsdoc
      - name: Fetch branches
        run: git fetch
      - name: Generate specification
        run: node openapi-generator.js
      - name: Remove unwanted changes
        run: git checkout package*
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          labels: automerge
          delete-branch: true
          body: Update OpenAPI specification
          title: Update OpenAPI specification
          commit-message: Update OpenAPI specification
          branch: update-openapi
      - name: Deploy to gh-pages
        run: |
          mv multidashboard-api{,2}.json
          git checkout gh-pages
          mv multidashboard-api{2,}.json
          [[ -z $(git status --untracked-files=no --porcelain) ]] && echo "no changes, exiting" && exit 0;
          git add -f multidashboard-api.json
          git -c user.name="Shubham Jain" -c user.email="shubham@sjain.dev" commit -m "Deploy OpenAPI specification"
          git push origin gh-pages
