name: Deploy backend API spec

on:
  push:
    branches:
      - main
jobs:
  deploy-backend-api-spec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install swagger-jsdoc
        run: npm install swagger-jsdoc
      - name: Generator specification
        run: node openapi-generator.js && ls && pwd
      - name: Deploy Spec
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'care-quality-dashboard-api.json'
          destination_repo: 'COMP0016_2020_21_Team20/COMP0016_2020_21_Team20'
          destination_branch: 'gh-pages'
          user_email: 'shubham@sjain.dev'
          user_name: 'shu8'
