name: Publish Docker image to GitHub Packages & deploy on server
on:
  push:
    branches: 'main'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Create Prisma env file
        run: |
          touch .env
          echo NEXT_PUBLIC_KEYCLOAK_USER_ACCOUNT_MANAGE_URL=${{ secrets.NEXT_PUBLIC_KEYCLOAK_USER_ACCOUNT_MANAGE_URL }} >> .env
      - name: Build & Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: uclcomputerscience/comp0016_2020_21_team20/care-quality-dashboard-web
          tags: latest
      - name: Rebuild & restart containers on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: docker-compose -f ${{ secrets.DOCKER_COMPOSE_FILE }} pull && docker-compose -f ${{ secrets.DOCKER_COMPOSE_FILE }} up -d --build
