name: Deploy backend API spec

on:
  push:
    branches:
      - main
jobs:
  deploy-backend-api-spec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and Generate Spec
        run: |
          npm install swagger-jsdoc
          node openapi-generator.js
      - name: Deploy Spec
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ~/care-quality-dashboard-api.json
          TARGET_FOLDER: backend
          CLEAN: true
