name: Deploy backend API spec

on:
  push:
    branches:
      - main
jobs:
  deploy-backend-api-spec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install swagger-jsdoc
        run: npm install swagger-jsdoc
      - name: Fetch branches
        run: git fetch
      - name: Generator specification
        run: node openapi-generator.js
      - name: Deploy Spec
        run: |
          git checkout .
          mv care-quality-dashboard-api{,2}.json
          git checkout gh-pages
          mv care-quality-dashboard-api{2,}.json
          [[ -z $(git status --untracked-files=no --porcelain) ]] && echo "no changes, exiting" && exit 0;
          git add -f care-quality-dashboard-api.json
          git -c user.name="Shubham Jain" -c user.email="shubham@sjain.dev" commit -m "Deploy OpenAPI specification"
          git push origin gh-pages
