name: Deploy backend API spec

on:
  push:
    branches:
      - main
jobs:
  deploy-backend-api-spec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install swagger-jsdoc
        run: npm install swagger-jsdoc
      - name: Generator specification
        run: node openapi-generator.js && ls && pwd
      - name: Deploy Spec
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Deploy OpenAPI specification
          branch: gh-pages
          file_pattern: care-quality-dashboard-api.json
          commit_user_name: Shubham Jain
          commit_user_email: shubham@sjain.dev
          push_options: '--force'
