name: Publish Docker image to GitHub Packages
on:
  push:
    branches: 'main'
jobs:
  push_to_github_packages:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build & Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: uclcomputerscience/comp0016_2020_21_team20/nhsw-self-assessment-web
          tags: latest
          tag_with_ref: true
