name: Test backend API

on: pull_request
jobs:
  test-backend-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start Docker containers
        run: docker-compose -f docker-compose-test.yml up -d
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run backend:test
