name: Test frontend components

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-frontend-components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1 # Install dependencies, with cache
      - name: Test
        run: npm run test:frontend
