name: Test entire platform on Chrome (end-to-end)

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-end-to-end-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: '10'
      - uses: bahmutov/npm-install@v1 # Install dependencies, with cache
        with:
          node-version: '10'
      - name: Start Docker containers
        run: docker-compose -f docker-compose-e2e-test.yml up -d
      - name: Test
        run: npm run test:e2e
